# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cb40954a345964d319dceebd772f9cc856a7a64f2fea826bb3a5844f449ab86eee9219ca8f0bf15be04911d0274c1702cd8ccc58640654ab3b1361afa1612aa

test:
  secret_key_base: e8a6deaba0419ff91277a1b85fcc5144fa508e88811f441adbbf6262e58a5b476c2bc4beb802663cbd2c35b88f9792c00cbb9ed785ce681ff46a48292e859c41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
